In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a, type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [7]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [8]:
# 벡터화
tic = time.time() # 현재 시간 c 측정
c = np.dot(a, b) # W_t(transpose) * X ; 내장함수
toc = time.time()

print(c)
print('Vectorized version : ' + str(1000*(toc-tic)) + 'ms')

249855.19309672536
Vectorized version : 2.0911693572998047ms


In [9]:
# 비벡터화 ; 벡터화보다 약 300배 오래걸림
c = 0
tic = time.time()
for i in range(1000000) :  # 명시적 for문
    c += a[i]*b[i]
toc = time.time()

print(c)
print('For loop : ' + str(1000*(toc-tic)) + 'ms')

249855.19309672766
For loop : 599.9736785888672ms


In [2]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage = 100*A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [23]:
import numpy as np
a = np.random.randn(5)

In [8]:
print(a ,a.shape) # 1차원 벡터

[ 0.02083303  1.33330388 -0.03310454 -0.06769971  0.37342   ] (5,)


In [10]:
print(a.T, a.T.shape)

[ 0.02083303  1.33330388 -0.03310454 -0.06769971  0.37342   ] (5,)


In [11]:
print(np.dot(a, a.T))

1.923254911064244


In [24]:
a = a.reshape(5, 1) # 1차원 a

In [20]:
a = np.random.randn(5, 1) # column vector
print(a, a.shape)

[[2.82365067]
 [0.635375  ]
 [0.14367704]
 [0.83350043]
 [1.78758275]] (5, 1)


In [22]:
print(a.T) # row vector

[[2.82365067 0.635375   0.14367704 0.83350043 1.78758275]]


In [21]:
assert(a.shape == (5, 1)) # 2차원 a